### ISSUE TITLE
Add an image to my template

### ISSUE THREAD

**Issue by bbinet** [djakish/render-typst#2]
Fist thank you for this project which is great to compile typst template directly in the browser.
I need to add images to my typst document: how would you do it using render-typst?

**Comment by djakish** [comment]
Hello, the current way I managed to do it is convert image file to bytes and pass it to source like this: 
 
`#image(bytes(string of bytes here))`
 
 But it is quite slow even for smaller images, I'll try to figure out how to do it in a proper way.

**Comment by bbinet** [comment]
I also came across the [typst.ts](https://github.com/Myriad-Dreamin/typst.ts) project which seem to be able to insert images through their mapShadow api (see serverless in-browser example here: https://myriad-dreamin.github.io/typst.ts/cookery/guide/compiler/serverless.html) if it can help.

**Comment by djakish** [comment]
I think I got it, added example in demo. Can you check out the latest commit or npm version. Also I think the reason the passing bytes as text was slow is because I was rendering it as SVG and not a PNG.

**Comment by bbinet** [comment]
Thank you @djakish !
I will test the image feature this week and report back here.

**Comment by bbinet** [comment]
This works perfectly now with an image, thanks!
