### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by soerface** [djakish/render-typst#3]
Thanks for your work!

I couldn't find any information about the license of your bindings. Would you mind adding a LICENSE file / `license` field to Cargo.toml to clarify the terms under which your package can be used?

Probably Apache 2.0 is the most straightforward choice, as typst itself and other bindings like the python bindings are licensed with it:

- https://github.com/typst/typst/blob/main/LICENSE
- https://github.com/messense/typst-py/blob/main/LICENSE

**Comment by djakish** [comment]
Added the license, also thank you for your pull request.
